knpu_oauth2_client:
    clients:
  
        keycloak : # Ce nom est un identifiant pour votre client
            type: keycloak
            client_id: '%env(KEYCLOAK_CLIENTID)%'
            client_secret: '%env(KEYCLOAK_SECRET)%'
            auth_server_url: '%env(KEYCLOAK_APP_URL)%'
            realm: 'Myapplis'
            redirect_route: 'oauth_check'
            use_state: false